codesnug_project/codesnug/urls.py
from django.conf.urls import patterns, include, url
from codesnug.users.forms import UserRegistrationForm
from registration.backends.default.views import RegistrationView
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import views as auth_views
from goals.decorators import add_workspace_ajax, add_tag_ajax
from users.decorators import update_user_first_name, update_user_last_name, update_user_email, update_user_birth_date, \
    update_user_password, update_workspace_permission

from codesnug.views import Home, TermsConditions, Faqs, Api, TheProject, Privacy, ContactUs, WhoWeAre

from codesnug.goals.views import WorkspaceList, WorkspaceCreate, WorkspacePermissionsCreate, \
    GoalCreate, WorkspaceDetail, GoalList, GoalDetail, GoalUpdate, GoalDelete, WorkspaceUpdate, WorkspaceDelete, TagList, \
    TagCreate, TagDetail, TagUpdate, TagDelete, SnippetDetail, DataDownload, SnippetDownload, GoalDownload

from codesnug.search.views import GoalSearchResults

from codesnug.users.views import UserGroupList, UserGroupCreate, UserGroupDetail, \
    AddUserToGroupView, Profile, UserGroupUpdate, UserGroupDelete

from haystack.views import SearchView, search_view_factory
from codesnug.search.forms import GoalSearchForm

from rest_framework import routers

from codesnug.api.views import GoalViewSet, SnippetViewSet, MyUserViewSet, WorkspaceViewSet, TagViewSet

admin.autodiscover()

urlpatterns = patterns('',
                       # pages
                       url(r'^$', Home.as_view(),
                           name='home'),
                       url(r'^help/faqs/$', Faqs.as_view(),
                           name='help_faqs'),
                       url(r'^help/api/$', Api.as_view(),
                           name='help_api'),
                       url(r'^about/the-project/$', TheProject.as_view(),
                           name='the_project'),
                       url(r'^about/terms-and-conditions/$', TermsConditions.as_view(),
                           name='terms_conditions'),
                       url(r'^about/privacy/$', Privacy.as_view(),
                           name='privacy'),
                       url(r'^contact/$', ContactUs.as_view(),
                           name='contact_us'),
                       url(r'^contact/who-we-are/$', WhoWeAre.as_view(),
                           name='who_we_are'),
                       )

urlpatterns += patterns('',
                        # built-in
                        (r'^i18n/', include('django.conf.urls.i18n')),
                        url(r'^admin/', include(admin.site.urls)),
                        )

urlpatterns += patterns('',
                        # Registration
                        url(r'^accounts/profile/$', Profile.as_view(),
                            name='profile'),
                        url(r'^accounts/register/$', RegistrationView.as_view(form_class=UserRegistrationForm),
                            name='registration_register'),
                        (r'^accounts/', include('registration.backends.default.urls')),
                        url(r'^login/$', auth_views.login, {'template_name': 'registration/login.html'},
                            name='auth_login'),
                        url(r'^logout/$', auth_views.logout, {'template_name': 'registration/logout.html'},
                            name='auth_logout'),
                        url(r'^password/change/$', auth_views.password_change,
                            {'post_change_redirect': reverse_lazy('password_change_done')},
                            name='password_change'),
                        url(r'^password/change/done/$', auth_views.password_change_done,
                            name='password_change_done'),
                        url(r'^password/reset/$', auth_views.password_reset,
                            {'post_reset_redirect': reverse_lazy('password_reset_done')},
                            name='password_reset'),
                        url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
                            auth_views.password_reset_confirm,
                            name='password_reset_confirm'),
                        url(r'^password/reset/complete/$', auth_views.password_reset_complete,
                            {'post_reset_redirect': reverse_lazy('password_reset_complete')},
                            name='password_reset_complete'),
                        url(r'^password/reset/done/$', auth_views.password_reset_done,
                            name='password_reset_done'),
                        )

urlpatterns += patterns('',
                        # Users
                        url(r'^edit_first_name$', update_user_first_name,
                            name='edit_first_name_ajax'),
                        url(r'^edit_last_name$', update_user_last_name,
                            name='edit_last_name_ajax'),
                        url(r'^edit_email$', update_user_email,
                            name='edit_email_ajax'),
                        url(r'^edit_birth_date$', update_user_birth_date,
                            name='edit_birth_date_ajax'),
                        url(r'^edit_password$', update_user_password,
                            name='edit_password_ajax'),

                        #Download Data
                        url(r'^download-data/$', DataDownload.as_view(),
                            name='download_data'),
                        url(r'^(?P<username>[^/]+)/download-snippet/(?P<uuid>[^/]+)/$', SnippetDownload.as_view(),
                            name='download_snippet'),
                        url(r'^(?P<username>[^/]+)/download-goal/(?P<uuid>[^/]+)/$', GoalDownload.as_view(),
                            name='download_goal'),

                        #UserGroups
                        url(r'^app/(?P<username>[^/]+)/usergroups/$', UserGroupList.as_view(),
                            name='usergroups_list'),
                        url(r'^usergroups/add/$', UserGroupCreate.as_view(),
                            name='usergroups_add'),
                        url(r'^app/(?P<username>[^/]+)/usergroups/(?P<uuid>[^/]+)/$', UserGroupDetail.as_view(),
                            name='usergroup_detail'),
                        url(r'^app/(?P<username>[^/]+)/usergroups/(?P<uuid>[^/]+)/edit/$', UserGroupUpdate.as_view(),
                            name='usergroup_update'),
                        url(r'^app/(?P<username>[^/]+)/usergroups/(?P<uuid>[^/]+)/delete/$', UserGroupDelete.as_view(),
                            name='usergroup_delete'),
                        url(r'^app/(?P<username>[^/]+)/usergroups/(?P<uuid>[^/]+)/add-workspace/$',
                            WorkspacePermissionsCreate.as_view(),
                            name='asign_workspace_group'),
                        url(r'^app/(?P<username>[^/]+)/usergroups/(?P<uuid>[^/]+)/add-user/$', AddUserToGroupView.as_view(),
                            name='asign_user_group'),

                        url(r'^edit_workspace_permission$', update_workspace_permission,
                            name='edit_workspace_permission'),
                        )

urlpatterns += patterns('',
                        # goals
                        url(r'^app/(?P<username>[^/]+)/goals/$', GoalList.as_view(),
                            name='goals_list'),
                        url(r'^goals/add/$', GoalCreate.as_view(),
                            name='goals_add'),
                        url(r'^app/(?P<username>[^/]+)/goals/(?P<uuid>[^/]+)/$', GoalDetail.as_view(),
                            name='goal_detail'),
                        url(r'^app/(?P<username>[^/]+)/goals/(?P<goal_uuid>[^/]+)/snippet/(?P<uuid>[^/]+)/$',
                            SnippetDetail.as_view(),
                            name='snippet_detail'),
                        url(r'^app/(?P<username>[^/]+)/goals/(?P<uuid>[^/]+)/edit/$', GoalUpdate.as_view(),
                            name='goal_update'),
                        url(r'^app/(?P<username>[^/]+)/goals/(?P<uuid>[^/]+)/delete/$', GoalDelete.as_view(),
                            name='goal_delete'),

                        #goals search
                        #(r'^search/', include('haystack.urls')),
                        #url(r'^search-test/$', GoalSearchResults.as_view(), name='search_test'),


                        #Workspaces
                        url(r'^app/(?P<username>[^/]+)/workspaces/$', WorkspaceList.as_view(),
                            name='workspaces_list'),
                        url(r'^workspaces/add/$', WorkspaceCreate.as_view(),
                            name='workspaces_add'),
                        url(r'^app/(?P<username>[^/]+)/workspaces/(?P<uuid>[^/]+)/$', WorkspaceDetail.as_view(),
                            name='workspace_detail'),
                        url(r'^app/(?P<username>[^/]+)/workspaces/(?P<uuid>[^/]+)/edit/$', WorkspaceUpdate.as_view(),
                            name='workspace_update'),
                        url(r'^app/(?P<username>[^/]+)/workspaces/(?P<uuid>[^/]+)/delete/$', WorkspaceDelete.as_view(),
                            name='workspace_delete'),
                        url(r'^add-workspace$', add_workspace_ajax,
                            name='workspace_add_ajax'),

                        #Tags
                        url(r'^app/(?P<username>[^/]+)/tags/$', TagList.as_view(),
                            name='tags_list'),
                        url(r'^tags/add/$', TagCreate.as_view(),
                            name='tags_add'),
                        url(r'^app/(?P<username>[^/]+)/tags/(?P<uuid>[^/]+)/$', TagDetail.as_view(),
                            name='tag_detail'),
                        url(r'^app/(?P<username>[^/]+)/tags/(?P<uuid>[^/]+)/edit/$', TagUpdate.as_view(),
                            name='tag_update'),

codesnug_project/codesnug/api/models.py
from django.db import models

# Create your models here.

codesnug_project/codesnug/search/models.py
from django.db import models

# Create your models here.

codesnug_project/codesnug/users/models.py
# -*- coding: utf-8 -*-
import logging
from django.core.exceptions import ValidationError
from django.utils.decorators import method_decorator
from registration.signals import user_registered
from dateutil import parser

from uuidfield import UUIDField
from codesnug.settings import MAX_UPLOAD_SIZE
from django.contrib.auth.models import AbstractUser, AbstractBaseUser, UserManager, PermissionsMixin

import os
import re
from awesome_avatar.settings import config
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.db import models
from awesome_avatar.fields import AvatarField
from codesnug.users.storage import OverwriteStorage
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.core import validators
from django.core.mail import send_mail
from django.utils.http import urlquote

try:
    from cStringIO import StringIO
except ImportError:
    from StringIO import StringIO

try:
    from PIL import Image
except ImportError:
    from PIL import Image

logger = logging.getLogger(__name__)


def get_image_path(instance, filename):
    return os.path.join('avatars', str(instance.username), filename)


class MyUser(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(_('username'), max_length=30, unique=True,
                                help_text=_('Required. 30 characters or fewer. Letters, numbers and '
                                            '@/./+/-/_ characters'),
                                validators=[
                                    validators.RegexValidator(re.compile('^[\w.@+-]+$'),
                                                              _('Enter a valid username.'), 'invalid')
                                ])
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    email = models.EmailField(_('email address'), blank=False, unique=True)
    is_staff = models.BooleanField(_('staff status'), default=False,
                                   help_text=_('Designates whether the user can log into this admin '
                                               'site.'))
    is_active = models.BooleanField(_('active'), default=True,
                                    help_text=_('Designates whether this user should be treated as '
                                                'active. Unselect this instead of deleting accounts.'))
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    date_of_birth = models.DateField(null=True)
    uuid = UUIDField(auto=True)
    avatar = AvatarField(upload_to=get_image_path,
                         storage=OverwriteStorage(),
                         width=200,
                         height=200,
                         default='avatars/default.jpg')

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def __unicode__(self):
        return self.username

    def get_absolute_url(self):
        return "/users/%s/" % urlquote(self.username)

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        "Returns the short name for the user."
        return self.first_name

    def email_user(self, subject, message, from_email=None):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email])


class UserGroupManager(models.Manager):
    def create_user_group(self, title, owner, description=''):

        if title is None or title is '':
            raise ValidationError('Usergroup title must be set')
        if owner is None:
            raise ValidationError('Owner must be set')

        usergroup = self.create(title=title, owner=owner)
        usergroup.description = description
        return usergroup


class UserGroup(models.Model):
    title = models.CharField(max_length=200)
    owner = models.ForeignKey(MyUser, related_name='owned_groups')
    description = models.TextField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    users = models.ManyToManyField(MyUser, blank=True, null=True)
    uuid = UUIDField(auto=True)

    objects = UserGroupManager()

    def save(self, *args, **kwargs):
        self.full_clean()
        super(UserGroup, self).save(*args, **kwargs)

    class Meta:
        unique_together = (("title", "owner"),)
        ordering = ('created_at', )


def user_registered_callback(sender, user, request, **kwargs):

    if 'first_name' in request.POST:
        user.first_name = request.POST.get('first_name', None)
    if 'last_name' in request.POST:
        user.last_name = request.POST.get('last_name', None)

    user.date_of_birth = parser.parse(request.POST.get('date_of_birth', None))

    user.save()

    if 'avatar' in request.FILES:

        avatar_file = request.FILES['avatar']
        if avatar_file.size > int(MAX_UPLOAD_SIZE):
            return

        x1 = request.POST.get('avatar-x1', 0)
        y1 = request.POST.get('avatar-y1', 0)
        x2 = request.POST.get('avatar-x2', x1)
        y2 = request.POST.get('avatar-y2', y1)
        ratio = request.POST.get('avatar-ratio', 1)
        ratio = float(1 if not ratio else ratio)

        box_raw = [x1, y1, x2, y2]
        box = []

        for coord in box_raw:
            try:
                coord = int(coord)
            except ValueError:
                coord = 0

            if ratio > 1:
                coord = int(coord * ratio)
            box.append(coord)

        image = Image.open(StringIO(avatar_file.read()))
        image = image.crop(box)
        if not getattr(config, 'no_resize', False):
            image = image.resize((config.width, config.height), Image.ANTIALIAS)

        content = StringIO()
        image.save(content, config.save_format, quality=config.save_quality)

        file_name = u'{}.{}'.format(os.path.splitext(avatar_file.name)[0], config.save_format)

        # new_data = SimpleUploadedFile(file.name, content.getvalue(), content_type='image/' + config.save_format)
        new_data = InMemoryUploadedFile(content, None, 'avatar.'+config.save_format, 'image/' + config.save_format, len(content.getvalue()), None)

        user.avatar = new_data

        user.save()

user_registered.connect(user_registered_callback)

codesnug_project/codesnug/forms.py
__author__ = 'rene'

from django import forms
from captcha.fields import ReCaptchaField


class ContactForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)
    captcha = ReCaptchaField(attrs={'theme' : 'clean'})

codesnug_project/codesnug/search/forms.py
from haystack.forms import SearchForm

__author__ = 'rene'

class GoalSearchForm(SearchForm):

    def no_query_found(self):
        return self.searchqueryset.all()

    def search(self):
        # First, store the SearchQuerySet received from other processing. (the main work is run internally by Haystack here).
        sqs = super(GoalSearchForm, self).search()

        # if something goes wrong
        if not self.is_valid():
            return self.no_query_found()

        # you can then adjust the search results and ask for instance to order the results by title
        sqs = sqs.order_by('title')

        return sqs

codesnug_project/codesnug/templates/api.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}
{% load custom_filters %}
{% load widget_tweaks %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb_for contact_us %}
        <i class="glyphicon glyphicon-wrench"></i> {% trans "The Codesnug API" %}
    {% endbreadcrumb_for %}
{% endblock %}

{% block title %}CodeSnug | {% trans 'Our API' %}{% endblock %}

{% block meta_message %}
    {% trans 'Store and share your code' %}
{% endblock %}

{% block header %}
    {{ form.media }}
    <link href="{% static 'css/datepicker.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container">
<div class="row" id="main-content">
    <div class="col-md-12">

        <div class="page-header">
            <h2>{% trans 'Our API' %}</h2>
        </div>
        {% render_breadcrumbs "breadcrumbs.html" %}

        {% include "messages.html" %}

        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>{% trans 'Our API' %}</h3>
                        {% blocktrans %}
                        <p>Codesnug dispone de una API REST de consulta para acceder a los datos de un usuario.</p>

                        <p>Formatos de retorno de la API:</p>
                        <ol>
                            <li>application/json</li>
                            <li>text/html</li>
                        </ol>
                        {% endblocktrans %}
                        {% blocktrans %}
                        <p>Entre las operaciones que permite la API se encuentran las siguientes operaciones:</p>
                        <ol>
                            <li><strong>GET /api/goals</strong>: Obtiene la lista de goals del usuario actual.</li>
                            <li><strong>GET /api/goals/{uuid}</strong>: Obtiene la información del Goal identificado mediante su uuid.</li>
                            <li><strong>GET /api/workspaces</strong>: Obtiene un listado con todos los Espacios de trabajo del usuario actual.</li>
                            <li><strong>GET /api/workspaces/{uuid}</strong>: Obtiene la información de un Espacio de trabajo identificado por su uuid.</li>
                            <li><strong>GET /api/snippets</strong>: Obtiene un listado de los snippets del usuario actual.</li>
                            <li><strong>GET /api/snippets/{uuid}</strong>: Obtiene la información de un snippet en concreto dado su uuid.</li>
                            <li><strong>GET /api/tags</strong>: Obtiene un listado de las etiquetas del usuario actual.</li>
                            <li><strong>GET /api/tags/{uuid}</strong>: Obtiene la información de una etiqueta en concreto dado su uuid.</li>
                        </ol>
                        {% endblocktrans %}
                        {% blocktrans %}
                        <p>Todas las peticiones deben incluir las credenciales del usuario, que serán cifradas utilizando SSL.</p>
                        <p>Ejemplo de petición:</p>
                        <pre><code>https://codesnug.com/api/goals -u user:pass</code></pre>
                        <p>Ejemplo de respuesta:</p>
                        <pre><code>
HTTP 200 OK
    Content-Type: application/json
    Vary: Accept
    Allow: GET, HEAD, OPTIONS


{
    "count": 6,
    "next": null,
    "previous": null,
    "results": [
    {
        "title": "Goal 1",
        "description": "Maecenas laoreet orci justo, ut sagittis neque varius eu. Nullam risus sapien, cursus id magna vitae, blandit semper nisi.",
        "uuid": "8b5eb590d0094c529f547ea7f17dcf86",
        "created_at": "2014-07-21T13:18:31.506Z",
        "is_private": false,
        "owner": "nombre_usuario",
        "snippets": [
            "4c46864b9f3c4a89b1aee6bf50f04a5f",
            "572d5029abb54d1fa225f0c44e9fe44d"
        ],
        "workspaces": [
            "Workspace 1",
            "Workspace 2"
        ],
        "tags": [
            "Tag 1",
            "Tag 2"
        ]
    },
...
                        </code></pre>
                        {% endblocktrans %}
                        {% blocktrans %}<p>Para hacer pruebas con la información ofrecida por la API, está disponible una interfaz web para realizar las consultas.</p>{% endblocktrans %}
                        <p><a href="{% url 'api-root' %}" class="btn-sm btn-primary">{% blocktrans %}Browsable API{% endblocktrans %}</a></p>
                        {% blocktrans %}<p>Debes estar registrado para acceder a la API navegable.</p>{% endblocktrans %}

                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
    </div>
{% endblock %}

{% block footer %}

    <script src="{% static 'bootflat/js/icheck.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            $('.checkbox input').iCheck({
                checkboxClass: 'icheckbox_flat',
                increaseArea: '20%'
            });

            $('#id_date_of_birth').datepicker();

        });
    </script>
{% endblock %}

codesnug_project/codesnug/templates/breadcrumbs.html
<ol class="breadcrumb">
    {% for url, label in breadcrumbs %}
        <li {% if forloop.last %} class="active" {% endif %}>{% ifnotequal forloop.counter breadcrumbs_total %}<a href="{{ url }}">{{ label|safe }}</a>
            {% else %}<span>{{ label|safe }}</span>
            {% endifnotequal %}
        </li>
    {% endfor %}
</ol>

codesnug_project/codesnug/templates/contact_us.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}
{% load custom_filters %}
{% load widget_tweaks %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb_for contact_us %}
        <i class="glyphicon glyphicon-send"></i> {% trans "Contact us" %}
    {% endbreadcrumb_for %}
{% endblock %}

{% block title %}CodeSnug | {% trans 'Contact us' %}{% endblock %}

{% block header %}
    {{ form.media }}
{% endblock %}

{% block content %}
<div class="container">
<div class="row" id="main-content">
    <div class="col-md-12">

        <div class="page-header">
            <h2>{% trans 'Contact us' %}</h2>
        </div>
        {% render_breadcrumbs "breadcrumbs.html" %}

        {% include "messages.html" %}

        <div class="row">
            <div class="col-md-9">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form action="." method="post">
                            {% csrf_token %}
                            <div class="form-group {% if form.name.errors %} has-error {% endif %}">
                                <label for="id_name" class="control-label">{% trans "Name" %}</label>
                                {{ form.name|addcss:'form-control' }}
                                {% if form.name.errors %}
                                    <ul class="help-block">
                                        {% for error in form.name.errors %}
                                            <li>{{ error|escape }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            </div>
                            <div class="form-group {% if form.email.errors %} has-error {% endif %}">
                                <label for="id_email" class="control-label required">{% trans "Email" %}</label>
                                {{ form.email|addcss:'form-control' }}
                                {% if form.email.errors %}
                                    <ul class="help-block">
                                        {% for error in form.email.errors %}
                                            <li>{{ error|escape }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            </div>
                            <div class="form-group {% if form.message.errors %} has-error {% endif %}" id="message-group">
                                <label for="id_message" class="control-label">{% trans "Message" %}</label>
                                {{ form.message|attr:"rows:5"|addcss:'form-control' }}
                                {% if form.message.errors %}
                                    <ul class="help-block">
                                        {% for error in form.message.errors %}
                                            <li>{{ error|escape }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            </div>
                            <div class="form-group {% if form.captcha.errors %} has-error {% endif %}" id="captcha-group">
                                <label for="id_captcha" class="control-label">{% trans "Captcha" %}</label>
                                {{ form.captcha|addcss:'form-control' }}
                                {% if form.captcha.errors %}
                                    <ul class="help-block">
                                        {% for error in form.captcha.errors %}
                                            <li>{{ error|escape }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">{% trans 'Send message' %}</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <h4>{% trans 'Hello there!' %}</h4>
                <p>{%  blocktrans %}Do you have something to tell us? Do you have a suggestion? Did you find a bug? Say thanks maybe?{% endblocktrans %}</p>
                <p>{%  blocktrans %}Whatever, you can us this form to stay in touch with us!{% endblocktrans %}</p>
            </div>
        </div>

    </div>
</div>
    </div>
{% endblock %}

{% block footer %}

    <script src="{% static 'bootflat/js/icheck.min.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            $('.checkbox input').iCheck({
                checkboxClass: 'icheckbox_flat',
                increaseArea: '20%'
            });

            $('#id_date_of_birth').datepicker();

        });
    </script>
{% endblock %}

codesnug_project/codesnug/templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{% if message.tags == 'success'%}{{ message.tags }}
                {% elif message.tags == 'error' %}danger{% endif %}">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

codesnug_project/codesnug/templates/the_project.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}
{% load custom_filters %}
{% load widget_tweaks %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb_for contact_us %}
        <i class="glyphicon glyphicon-briefcase"></i> {% trans "The Project" %}
    {% endbreadcrumb_for %}
{% endblock %}

{% block title %}CodeSnug | {%  trans 'The Project' %}{% endblock %}

{% block content %}
<div class="container">
<div class="row" id="main-content">
    <div class="col-md-12">

        <div class="page-header">
            <h2>{% trans 'About the project' %}</h2>
        </div>
        {% render_breadcrumbs "breadcrumbs.html" %}

        {% include "messages.html" %}

        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>{% trans 'Some words about this project' %}</h3>
                        {% blocktrans %}
                        <p>My name is René F. Sánchez and Codesnug is my final Master's Degree Project. I studied the
                            Master's Degree in Web Engineering at the University of Oviedo in Spain and I thought (and still think)
                            that a project like this could be very useful and interesting.</p>
                        <p>As a programmer, I have lots and lots of snippets and sometimes is hard to find a place to store
                            and organize them. I wanted the possibility of access them both online and offline, so
                            developing a service with an online database and a web service was not a bad solution.</p>
                        <p>Many other services are focused on sharing, and it is hard to find your code on them.
                            In Codesnug we are focused on the storage but
                        also on sharing the snippets with small groups of people to collaborate.</p>
                        <p>Another point of Codesnug is that you can export all your code whenever you want.
                            We don't want to tie you to this platform and we'll make you things easy.</p>
                        {% endblocktrans %}
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
    </div>
{% endblock %}