codesnug_project/codesnug/urls.py
from django.conf.urls import patterns, include, url
from codesnug.users.forms import UserRegistrationForm
from registration.backends.default.views import RegistrationView
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import views as auth_views
from goals.decorators import add_workspace_ajax, add_tag_ajax
from users.decorators import update_user_first_name, update_user_last_name, update_user_email, update_user_birth_date, \
    update_user_password, update_workspace_permission

from codesnug.views import Home, TermsConditions, Faqs, Api, TheProject, Privacy, ContactUs, WhoWeAre

from codesnug.goals.views import WorkspaceList, WorkspaceCreate, WorkspacePermissionsCreate, \
    GoalCreate, WorkspaceDetail, GoalList, GoalDetail, GoalUpdate, GoalDelete, WorkspaceUpdate, WorkspaceDelete, TagList, \
    TagCreate, TagDetail, TagUpdate, TagDelete, SnippetDetail, DataDownload, SnippetDownload, GoalDownload

from codesnug.search.views import GoalSearchResults

from codesnug.users.views import UserGroupList, UserGroupCreate, UserGroupDetail, \
    AddUserToGroupView, Profile, UserGroupUpdate, UserGroupDelete

from haystack.views import SearchView, search_view_factory
from codesnug.search.forms import GoalSearchForm

from rest_framework import routers

from codesnug.api.views import GoalViewSet, SnippetViewSet, MyUserViewSet, WorkspaceViewSet, TagViewSet

admin.autodiscover()

urlpatterns = patterns('',
                       # pages
                       url(r'^$', Home.as_view(),
                           name='home'),
                       url(r'^help/faqs/$', Faqs.as_view(),
                           name='help_faqs'),
                       url(r'^help/api/$', Api.as_view(),
                           name='help_api'),
                       url(r'^about/the-project/$', TheProject.as_view(),
                           name='the_project'),
                       url(r'^about/terms-and-conditions/$', TermsConditions.as_view(),
                           name='terms_conditions'),
                       url(r'^about/privacy/$', Privacy.as_view(),
                           name='privacy'),
                       url(r'^contact/$', ContactUs.as_view(),
                           name='contact_us'),
                       url(r'^contact/who-we-are/$', WhoWeAre.as_view(),
                           name='who_we_are'),
                       )

urlpatterns += patterns('',
                        # built-in
                        (r'^i18n/', include('django.conf.urls.i18n')),
                        url(r'^admin/', include(admin.site.urls)),
                        )

urlpatterns += patterns('',
                        # Registration
                        url(r'^accounts/profile/$', Profile.as_view(),
                            name='profile'),
                        url(r'^accounts/register/$', RegistrationView.as_view(form_class=UserRegistrationForm),
                            name='registration_register'),
                        (r'^accounts/', include('registration.backends.default.urls')),
                        url(r'^login/$', auth_views.login, {'template_name': 'registration/login.html'},
                            name='auth_login'),
                        url(r'^logout/$', auth_views.logout, {'template_name': 'registration/logout.html'},
                            name='auth_logout'),
                        url(r'^password/change/$', auth_views.password_change,
                            {'post_change_redirect': reverse_lazy('password_change_done')},
                            name='password_change'),
                        url(r'^password/change/done/$', auth_views.password_change_done,
                            name='password_change_done'),
                        url(r'^password/reset/$', auth_views.password_reset,
                            {'post_reset_redirect': reverse_lazy('password_reset_done')},
                            name='password_reset'),
                        url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
                            auth_views.password_reset_confirm,
                            name='password_reset_confirm'),
                        url(r'^password/reset/complete/$', auth_views.password_reset_complete,
                            {'post_reset_redirect': reverse_lazy('password_reset_complete')},
                            name='password_reset_complete'),
                        url(r'^password/reset/done/$', auth_views.password_reset_done,
                            name='password_reset_done'),
                        )

urlpatterns += patterns('',
                        # Users
                        url(r'^edit_first_name$', update_user_first_name,
                            name='edit_first_name_ajax'),
                        url(r'^edit_last_name$', update_user_last_name,
                            name='edit_last_name_ajax'),
                        url(r'^edit_email$', update_user_email,
                            name='edit_email_ajax'),
                        url(r'^edit_birth_date$', update_user_birth_date,
                            name='edit_birth_date_ajax'),
                        url(r'^edit_password$', update_user_password,
                            name='edit_password_ajax'),

                        #Download Data
                        url(r'^download-data/$', DataDownload.as_view(),
                            name='download_data'),
                        url(r'^(?P<username>[^/]+)/download-snippet/(?P<uuid>[^/]+)/$', SnippetDownload.as_view(),
                            name='download_snippet'),
                        url(r'^(?P<username>[^/]+)/download-goal/(?P<uuid>[^/]+)/$', GoalDownload.as_view(),
                            name='download_goal'),

                        #UserGroups
                        url(r'^app/(?P<username>[^/]+)/usergroups/$', UserGroupList.as_view(),
                            name='usergroups_list'),
                        url(r'^usergroups/add/$', UserGroupCreate.as_view(),
                            name='usergroups_add'),
                        url(r'^app/(?P<username>[^/]+)/usergroups/(?P<uuid>[^/]+)/$', UserGroupDetail.as_view(),
                            name='usergroup_detail'),
                        url(r'^app/(?P<username>[^/]+)/usergroups/(?P<uuid>[^/]+)/edit/$', UserGroupUpdate.as_view(),
                            name='usergroup_update'),
                        url(r'^app/(?P<username>[^/]+)/usergroups/(?P<uuid>[^/]+)/delete/$', UserGroupDelete.as_view(),
                            name='usergroup_delete'),
                        url(r'^app/(?P<username>[^/]+)/usergroups/(?P<uuid>[^/]+)/add-workspace/$',
                            WorkspacePermissionsCreate.as_view(),
                            name='asign_workspace_group'),
                        url(r'^app/(?P<username>[^/]+)/usergroups/(?P<uuid>[^/]+)/add-user/$', AddUserToGroupView.as_view(),
                            name='asign_user_group'),

                        url(r'^edit_workspace_permission$', update_workspace_permission,
                            name='edit_workspace_permission'),
                        )

urlpatterns += patterns('',
                        # goals
                        url(r'^app/(?P<username>[^/]+)/goals/$', GoalList.as_view(),
                            name='goals_list'),
                        url(r'^goals/add/$', GoalCreate.as_view(),
                            name='goals_add'),
                        url(r'^app/(?P<username>[^/]+)/goals/(?P<uuid>[^/]+)/$', GoalDetail.as_view(),
                            name='goal_detail'),
                        url(r'^app/(?P<username>[^/]+)/goals/(?P<goal_uuid>[^/]+)/snippet/(?P<uuid>[^/]+)/$',
                            SnippetDetail.as_view(),
                            name='snippet_detail'),
                        url(r'^app/(?P<username>[^/]+)/goals/(?P<uuid>[^/]+)/edit/$', GoalUpdate.as_view(),
                            name='goal_update'),
                        url(r'^app/(?P<username>[^/]+)/goals/(?P<uuid>[^/]+)/delete/$', GoalDelete.as_view(),
                            name='goal_delete'),

                        #goals search
                        #(r'^search/', include('haystack.urls')),
                        #url(r'^search-test/$', GoalSearchResults.as_view(), name='search_test'),


                        #Workspaces
                        url(r'^app/(?P<username>[^/]+)/workspaces/$', WorkspaceList.as_view(),
                            name='workspaces_list'),
                        url(r'^workspaces/add/$', WorkspaceCreate.as_view(),
                            name='workspaces_add'),
                        url(r'^app/(?P<username>[^/]+)/workspaces/(?P<uuid>[^/]+)/$', WorkspaceDetail.as_view(),
                            name='workspace_detail'),
                        url(r'^app/(?P<username>[^/]+)/workspaces/(?P<uuid>[^/]+)/edit/$', WorkspaceUpdate.as_view(),
                            name='workspace_update'),
                        url(r'^app/(?P<username>[^/]+)/workspaces/(?P<uuid>[^/]+)/delete/$', WorkspaceDelete.as_view(),
                            name='workspace_delete'),
                        url(r'^add-workspace$', add_workspace_ajax,
                            name='workspace_add_ajax'),

                        #Tags
                        url(r'^app/(?P<username>[^/]+)/tags/$', TagList.as_view(),
                            name='tags_list'),
                        url(r'^tags/add/$', TagCreate.as_view(),
                            name='tags_add'),
                        url(r'^app/(?P<username>[^/]+)/tags/(?P<uuid>[^/]+)/$', TagDetail.as_view(),
                            name='tag_detail'),
                        url(r'^app/(?P<username>[^/]+)/tags/(?P<uuid>[^/]+)/edit/$', TagUpdate.as_view(),
                            name='tag_update'),

codesnug_project/codesnug/goals/models.py
# -*- coding: utf-8 -*-
from django.db import models
from codesnug.users.models import MyUser
from codesnug.users.models import UserGroup
from codesnug.settings import WORKSPACE_PERMISSIONS, LANGUAGE_CHOICES

from uuidfield import UUIDField


class Tag(models.Model):
    title = models.CharField(max_length=50, blank=False)
    owner = models.ForeignKey(MyUser, related_name='owned_tags')
    uuid = UUIDField(auto=True)

    def __unicode__(self):
        return self.title

    class Meta:
        unique_together = (("title", "owner"),)
        ordering = ('title', )


class Workspace(models.Model):
    owner = models.ForeignKey(MyUser, related_name='owned_workspaces')
    title = models.CharField(max_length=200, blank=False)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    uuid = UUIDField(auto=True)

    def __unicode__(self):
        return self.title

    class Meta:
        unique_together = (("title", "owner"),)
        ordering = ('title', )


class WorkspacePermissions(models.Model):

    group = models.ForeignKey(UserGroup, related_name='usergroups_permissions')
    workspace = models.ForeignKey(Workspace, related_name='usergroups_permissions')
    permission = models.IntegerField(max_length=3, choices=WORKSPACE_PERMISSIONS)
    uuid = UUIDField(auto=True)

    class Meta:
        unique_together = (("group", "workspace"),)


class Goal(models.Model):
    owner = models.ForeignKey(MyUser, related_name='owned_goals')
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(Tag, blank=True, related_name='goals')
    workspaces = models.ManyToManyField(Workspace, blank=True, related_name='goals')
    is_private = models.BooleanField(default=True)
    uuid = UUIDField(auto=True)

    class Meta:
        unique_together = (("title", "owner"),)
        ordering = ('created_at', )

    def __unicode__(self):
        return self.uuid.__unicode__()

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        url = reverse("goal_detail", args=[str(self.uuid), str(self.owner.username)])
        print url
        return url


class BaseSnippet(models.Model):
    language = models.CharField(max_length=100, choices=LANGUAGE_CHOICES)
    version_number = models.IntegerField(default=1)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    uuid = UUIDField(auto=True)

    def __unicode__(self):
        return self.uuid.__unicode__()

    class Meta:
        abstract = True
        ordering = ('created_at', )


class Snippet(BaseSnippet):
    author = models.ForeignKey(MyUser, related_name='owned_snippets')
    goal = models.ForeignKey(Goal, related_name='snippets')
    title = models.CharField(max_length=200)


class Version(BaseSnippet):
    author = models.ForeignKey(MyUser, related_name='owned_versions')
    snippet = models.ForeignKey(Snippet, related_name='versions')

    class Meta:
        unique_together = (("snippet", "version_number"),)

codesnug_project/codesnug/forms.py
__author__ = 'rene'

from django import forms
from captcha.fields import ReCaptchaField


class ContactForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)
    captcha = ReCaptchaField(attrs={'theme' : 'clean'})

codesnug_project/codesnug/api/views.py
from rest_framework.response import Response

__author__ = 'rene'
from codesnug.goals.models import Goal, Snippet, Workspace, Tag
from rest_framework import viewsets
from codesnug.api.serializers import GoalSerializer, SnippetSerializer, WorkspaceSerializer, TagSerializer

from codesnug.users.models import MyUser
from codesnug.api.serializers import MyUserSerializer


class WorkspaceViewSet(viewsets.ModelViewSet):
    serializer_class = WorkspaceSerializer
    lookup_field = 'uuid'

    def get_queryset(self):
        return Workspace.objects.filter(owner=self.request.user)

    def retrieve(self, request, *args, **kwargs):
        print "Retrieve workspace"
        self.object = self.get_object()
        serializer = self.get_serializer(self.object)
        return Response(serializer.data)


class TagViewSet(viewsets.ModelViewSet):
    serializer_class = TagSerializer
    lookup_field = 'uuid'

    def get_queryset(self):
        return Tag.objects.filter(owner=self.request.user)

    def retrieve(self, request, *args, **kwargs):
        print "Retrieve tag"
        self.object = self.get_object()
        serializer = self.get_serializer(self.object)
        return Response(serializer.data)


class GoalViewSet(viewsets.ModelViewSet):
    serializer_class = GoalSerializer
    lookup_field = 'uuid'

    def get_queryset(self):
        return Goal.objects.filter(owner=self.request.user)

    def retrieve(self, request, *args, **kwargs):
        print "Retrieve goal"
        self.object = self.get_object()
        serializer = self.get_serializer(self.object)
        return Response(serializer.data)


class SnippetViewSet(viewsets.ModelViewSet):
    serializer_class = SnippetSerializer
    lookup_field = 'uuid'

    def get_queryset(self):
        return Snippet.objects.filter(goal__owner=self.request.user)

    def retrieve(self, request, *args, **kwargs):
        print "Retrieve snippet"
        self.object = self.get_object()
        serializer = self.get_serializer(self.object)
        return Response(serializer.data)


class MyUserViewSet(viewsets.ModelViewSet):

    serializer_class = MyUserSerializer
    lookup_field = 'username'

    def get_queryset(self):
        return MyUser.objects.all()

codesnug_project/codesnug/search/views.py
from django.shortcuts import render

# Create your views here.
from haystack.query import SearchQuerySet
from haystack.views import SearchView
from codesnug.goals.models import WorkspacePermissions


class GoalSearchResults(SearchView):
    """
    Search > Root
    """
    template = 'search/search_root.html'

    def user_can_view_goal(self, goal, user):
        print "can view?"
        if goal.owner == user:
            print "owner is user"
            return True

        try:
            workspace_permission = WorkspacePermissions.objects.get(workspace=goal.workspaces.all, group__users=user)
        except WorkspacePermissions.DoesNotExist:
            return False
        if workspace_permission and not goal.is_private:
            return True
        return False

    def build_form(self, form_kwargs=None):
        """
        Instantiates the form the class should use to process the search query.
        """
        data = None
        kwargs = {
            'load_all': self.load_all,
            }
        if form_kwargs:
            kwargs.update(form_kwargs)

        if len(self.request.GET):
            data = self.request.GET

        self.searchqueryset = SearchQuerySet().all()

        """for goal in self.searchqueryset:
            print goal.title"""

        if self.searchqueryset is not None:
            kwargs['searchqueryset'] = self.searchqueryset

        return self.form_class(data, **kwargs)

    def extra_context(self):
        """
        Allows the addition of more context variables as needed.

        Must return a dictionary.
        """
        results_list = list(self.results)
        #print results_list
        if self.searchqueryset is not None:
            for result in self.results:
                print result.object.get_absolute_url
                if not self.user_can_view_goal(result.object, self.request.user):
                    results_list.remove(result)
                    print "can not view goal " + result.object.title
                print results_list
            return {'total_count': len(results_list), 'results': results_list}
        else:
            return {}

codesnug_project/codesnug/templates/goals/content_goal.html
{% load i18n %}
{% load staticfiles %}
{% load custom_filters %}
<div class="row">
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="goal-title"><a href="{% url 'goal_detail' goal.owner.username goal.uuid %}" title="{{ goal.title }}">{{ goal.title }}</a></h3>
            </div>
            <div class="panel-body">
                <div class="goal-description"><p>{{ goal.description }}</p></div>
                <ul class="list-group">
                    {% for snippet in goal.snippets.all %}
                        <li class="list-group-item">
                            <div class="snippet-header">
                                <div class="btn-toolbar pull-right" role="toolbar">
                                    <div class="btn-group">
                                        <span class="label label-default">{{ snippet.get_language_display }}</span>
                                    </div>
                                </div>
                                <h4>{{ snippet.title }}</h4>
                            </div>
                            <div id="snippet-text-{{ snippet.uuid }}" class="snippet-text">{{ snippet.text }}</div>
                            <div class="btn-toolbar" role="toolbar">
                                <div class="btn-group">
                                    <form method="post" action="{% url 'download_snippet' request.user.username snippet.uuid %}">
                                        {% csrf_token %}
                                        <button class="btn btn-xs btn-info" type="submit">{% trans 'Download Snippet' %}</button>
                                    </form>
                                </div>
                            </div>
                            <script type="text/javascript">
                                var editor_{{ snippet.uuid }} = ace.edit("snippet-text-{{ snippet.uuid }}");
                                editor_{{ snippet.uuid }}.setTheme("ace/theme/chrome");
                                editor_{{ snippet.uuid }}.setReadOnly(true);
                                editor_{{ snippet.uuid }}.getSession().setMode("ace/mode/{{ snippet.language }}");
                                editor_{{ snippet.uuid }}.setOptions({
                                    maxLines: editor_{{ snippet.uuid }}.session.getLength()
                                });
                            </script>
                        </li>
                    {% endfor %}
                    <script type="text/javascript">
                    $(function() { // document ready
                        var button_font_up = $("#font_bigger_{{ goal.uuid }}");

                        button_font_up.click(function () {
                            {% for snippet in goal.snippets.all %}
                                editor_{{ snippet.uuid }}.setFontSize(editor_{{ snippet.uuid }}.getFontSize() + 2);
                            {% endfor %}
                        });

                        var button_font_down = $("#font_smaller_{{ goal.uuid }}");

                        button_font_down.click(function () {
                            {% for snippet in goal.snippets.all %}
                                editor_{{ snippet.uuid }}.setFontSize(editor_{{ snippet.uuid }}.getFontSize() - 2);
                            {% endfor %}
                        });
                    });
                    </script>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="btn-toolbar goal-toolbar">
            <div class="btn-group btn-group-sm">
                <button type="button" id="font_smaller_{{ goal.uuid }}" class="btn btn-default"><i class="glyphicon glyphicon-chevron-down"></i><i class="glyphicon glyphicon-font"></i></button>
                <button type="button" id="font_bigger_{{ goal.uuid }}" class="btn btn-default"><i class="glyphicon glyphicon-chevron-up"></i><i class="glyphicon glyphicon-font"></i></button>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">{% trans 'Goal Information' %}</div>
                <ul class="list-group">
                    <li class="list-group-item"><strong>{% trans 'Privacy:' %}</strong>{% if goal.is_private %}<span class="badge badge-danger">{% trans 'Private' %}</span>{% else %}<span class="badge badge-success">{% trans 'Public' %}</span>{% endif %}</li>
                    <li class="list-group-item"><strong>{% trans 'Number of snippets:' %}</strong> {{ goal.snippets.count }}</li>
                    <li class="list-group-item"><strong>{% trans 'Author:' %}</strong> {{ goal.owner.username }}</li>
                    <li class="list-group-item"><strong>{% trans 'Creation date:' %}</strong> {{ goal.created_at }}</li>
                </ul>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">{% trans 'Download' %}</div>
            <div class="panel-body text-center">
                <form method="post" action="{% url 'download_goal' goal.owner.username goal.uuid %}">
                    {% csrf_token %}
                    <button class="btn btn-info" type="submit" id="download_goal_{{ goal.uuid }}">{% trans 'Download Goal' %}</button>
                </form>
            </div>
        </div>
    </div>
</div>

codesnug_project/codesnug/templates/goals/tag_form.html
{% extends "goals/tag_list.html" %}
{% load i18n %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}
{% load custom_filters %}
{% load widget_tweaks %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb_for 'tag_add' %}
        <i class="glyphicon glyphicon-plus"></i> {% trans "Add New" %}
    {% endbreadcrumb_for %}
{% endblock %}

{% block title %}CodeSnug | {% trans 'Add new tag' %}{% endblock %}

{% block content %}
<div class="container">
<div class="row" id="main-content">
    {% include 'left_sidebar.html' %}

    <div id="main-column" class="col-md-9">

        <div class="page-header">
            <h2>{% trans 'Add new tag' %}</h2>
        </div>
        {% render_breadcrumbs "breadcrumbs.html" %}

        {% include "messages.html" %}

        <form action="" method="post">{% csrf_token %}
            <div class="form-group {% if form.title.errors %} has-error {% endif %}">
                <label for="id_title" class="control-label">{% trans "Workspace Title" %}</label>
                {{ form.title|addcss:'form-control' }}
                {% if form.username.errors %}
                    <ul class="help-block">
                        {% for error in form.title.errors %}
                            <li>{{ error|escape }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">{% trans 'Create Tag' %}</button>
            </div>
        </form>

    </div>
</div>
    </div>
{% endblock %}

{% block footer %}
    <script src="{% static 'bootflat/js/icheck.min.js' %}"></script>
    <script type="text/javascript">
        $(function() {
            $('.checkbox input').iCheck({
                checkboxClass: 'icheckbox_flat',
                increaseArea: '20%'
            });
        });
    </script>
{% endblock %}

codesnug_project/codesnug/templates/goals/workspace_form.html
{% extends "goals/workspace_list.html" %}
{% load i18n %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}
{% load custom_filters %}
{% load widget_tweaks %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb_for 'workspace_add' %}
        <i class="glyphicon glyphicon-plus"></i> {% trans "Add New" %}
    {% endbreadcrumb_for %}
{% endblock %}

{% block title %}CodeSnug | {% trans 'Add Workspace' %}{% endblock %}

{% block content %}
<div class="container">
<div class="row" id="main-content">
    {% include 'left_sidebar.html' %}

        <div id="main-column" class="col-md-9">

            <div class="page-header">
                <h2>{% trans "Add Workspace" %}</h2>
            </div>
            {% render_breadcrumbs "breadcrumbs.html" %}

            {% include "messages.html" %}

            <form action="" method="post">{% csrf_token %}
                <div class="form-group {% if form.title.errors %} has-error {% endif %}">
                    <label for="id_title" class="control-label">{% trans "Workspace Title" %}</label>
                    {{ form.title|addcss:'form-control' }}
                    {% if form.username.errors %}
                        <ul class="help-block">
                            {% for error in form.title.errors %}
                                <li>{{ error|escape }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
                <div class="form-group {% if form.description.errors %} has-error {% endif %}" id="description-group">
                    <label for="id_description" class="control-label">{% trans "Description" %}</label>
                    {{ form.description|attr:"rows:3"|addcss:'form-control' }}
                    {% if form.description.errors %}
                        <ul class="help-block">
                            {% for error in form.description.errors %}
                                <li>{{ error|escape }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary">{% trans 'Create Workspace' %}</button>
                </div>
            </form>

        </div>
</div>
    </div>
{% endblock %}

{% block footer %}
    <script src="{% static 'bootflat/js/icheck.min.js' %}"></script>
    <script type="text/javascript">
        $(function() {
            $('.checkbox input').iCheck({
                checkboxClass: 'icheckbox_flat',
                increaseArea: '20%'
            });
        });
    </script>
{% endblock %}

codesnug_project/codesnug/templates/goals/workspace_update_form.html
{% extends "goals/workspace_details.html" %}
{% load i18n %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}
{% load custom_filters %}
{% load widget_tweaks %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb_for 'workspace_update' object.owner.username object.uuid %}
        <i class="glyphicon glyphicon-edit"></i> {% trans "Edit" %}
    {% endbreadcrumb_for %}
{% endblock %}

{% block title %}CodeSnug | {{ object.title }} {% trans 'Edit' %}{% endblock %}

{% block content %}
<div class="container">
<div class="row" id="main-content">
        {% include 'left_sidebar.html' %}

        <div id="main-column" class="col-md-9">

            <div class="page-header">
                <h2>{{ object.title }} <small>{% trans 'Edit' %}</small></h2>
            </div>
            {% render_breadcrumbs "breadcrumbs.html" %}

            {% include "messages.html" %}

            <form action="" method="post">{% csrf_token %}
                <div class="form-group {% if form.title.errors %} has-error {% endif %}">
                    <label for="id_title" class="control-label">{% trans "Workspace Title" %}</label>
                    {{ form.title|addcss:'form-control' }}
                    {% if form.title.errors %}
                        <ul class="help-block">
                            {% for error in form.title.errors %}
                                <li>{{ error|escape }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
                <div class="form-group {% if form.description.errors %} has-error {% endif %}" id="description-group">
                    <label for="id_description" class="control-label">{% trans "Description" %}</label>
                    {{ form.description|attr:"rows:3"|addcss:'form-control' }}
                    {% if form.description.errors %}
                        <ul class="help-block">
                            {% for error in form.description.errors %}
                                <li>{{ error|escape }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary">{%  trans 'Update Workspace' %}</button>
                </div>
            </form>

        </div>
    </div>
    </div>
{% endblock %}

{% block footer %}
    <script src="{% static 'bootflat/js/icheck.min.js' %}"></script>
    <script type="text/javascript">
        $(function() {
            $('.checkbox input').iCheck({
                checkboxClass: 'icheckbox_flat',
                increaseArea: '20%'
            });
        });
    </script>
{% endblock %}