codesnug_project/codesnug/urls.py
from django.conf.urls import patterns, include, url
from codesnug.users.forms import UserRegistrationForm
from registration.backends.default.views import RegistrationView
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import views as auth_views
from goals.decorators import add_workspace_ajax, add_tag_ajax
from users.decorators import update_user_first_name, update_user_last_name, update_user_email, update_user_birth_date, \
    update_user_password, update_workspace_permission

from codesnug.views import Home, TermsConditions, Faqs, Api, TheProject, Privacy, ContactUs, WhoWeAre

from codesnug.goals.views import WorkspaceList, WorkspaceCreate, WorkspacePermissionsCreate, \
    GoalCreate, WorkspaceDetail, GoalList, GoalDetail, GoalUpdate, GoalDelete, WorkspaceUpdate, WorkspaceDelete, TagList, \
    TagCreate, TagDetail, TagUpdate, TagDelete, SnippetDetail, DataDownload, SnippetDownload, GoalDownload

from codesnug.search.views import GoalSearchResults

from codesnug.users.views import UserGroupList, UserGroupCreate, UserGroupDetail, \
    AddUserToGroupView, Profile, UserGroupUpdate, UserGroupDelete

from haystack.views import SearchView, search_view_factory
from codesnug.search.forms import GoalSearchForm

from rest_framework import routers

from codesnug.api.views import GoalViewSet, SnippetViewSet, MyUserViewSet, WorkspaceViewSet, TagViewSet

admin.autodiscover()

urlpatterns = patterns('',
                       # pages
                       url(r'^$', Home.as_view(),
                           name='home'),
                       url(r'^help/faqs/$', Faqs.as_view(),
                           name='help_faqs'),
                       url(r'^help/api/$', Api.as_view(),
                           name='help_api'),
                       url(r'^about/the-project/$', TheProject.as_view(),
                           name='the_project'),
                       url(r'^about/terms-and-conditions/$', TermsConditions.as_view(),
                           name='terms_conditions'),
                       url(r'^about/privacy/$', Privacy.as_view(),
                           name='privacy'),
                       url(r'^contact/$', ContactUs.as_view(),
                           name='contact_us'),
                       url(r'^contact/who-we-are/$', WhoWeAre.as_view(),
                           name='who_we_are'),
                       )

urlpatterns += patterns('',
                        # built-in
                        (r'^i18n/', include('django.conf.urls.i18n')),
                        url(r'^admin/', include(admin.site.urls)),
                        )

urlpatterns += patterns('',
                        # Registration
                        url(r'^accounts/profile/$', Profile.as_view(),
                            name='profile'),
                        url(r'^accounts/register/$', RegistrationView.as_view(form_class=UserRegistrationForm),
                            name='registration_register'),
                        (r'^accounts/', include('registration.backends.default.urls')),
                        url(r'^login/$', auth_views.login, {'template_name': 'registration/login.html'},
                            name='auth_login'),
                        url(r'^logout/$', auth_views.logout, {'template_name': 'registration/logout.html'},
                            name='auth_logout'),
                        url(r'^password/change/$', auth_views.password_change,
                            {'post_change_redirect': reverse_lazy('password_change_done')},
                            name='password_change'),
                        url(r'^password/change/done/$', auth_views.password_change_done,
                            name='password_change_done'),
                        url(r'^password/reset/$', auth_views.password_reset,
                            {'post_reset_redirect': reverse_lazy('password_reset_done')},
                            name='password_reset'),
                        url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
                            auth_views.password_reset_confirm,
                            name='password_reset_confirm'),
                        url(r'^password/reset/complete/$', auth_views.password_reset_complete,
                            {'post_reset_redirect': reverse_lazy('password_reset_complete')},
                            name='password_reset_complete'),
                        url(r'^password/reset/done/$', auth_views.password_reset_done,
                            name='password_reset_done'),
                        )

urlpatterns += patterns('',
                        # Users
                        url(r'^edit_first_name$', update_user_first_name,
                            name='edit_first_name_ajax'),
                        url(r'^edit_last_name$', update_user_last_name,
                            name='edit_last_name_ajax'),
                        url(r'^edit_email$', update_user_email,
                            name='edit_email_ajax'),
                        url(r'^edit_birth_date$', update_user_birth_date,
                            name='edit_birth_date_ajax'),
                        url(r'^edit_password$', update_user_password,
                            name='edit_password_ajax'),

                        #Download Data
                        url(r'^download-data/$', DataDownload.as_view(),
                            name='download_data'),
                        url(r'^(?P<username>[^/]+)/download-snippet/(?P<uuid>[^/]+)/$', SnippetDownload.as_view(),
                            name='download_snippet'),
                        url(r'^(?P<username>[^/]+)/download-goal/(?P<uuid>[^/]+)/$', GoalDownload.as_view(),
                            name='download_goal'),

                        #UserGroups
                        url(r'^app/(?P<username>[^/]+)/usergroups/$', UserGroupList.as_view(),
                            name='usergroups_list'),
                        url(r'^usergroups/add/$', UserGroupCreate.as_view(),
                            name='usergroups_add'),
                        url(r'^app/(?P<username>[^/]+)/usergroups/(?P<uuid>[^/]+)/$', UserGroupDetail.as_view(),
                            name='usergroup_detail'),
                        url(r'^app/(?P<username>[^/]+)/usergroups/(?P<uuid>[^/]+)/edit/$', UserGroupUpdate.as_view(),
                            name='usergroup_update'),
                        url(r'^app/(?P<username>[^/]+)/usergroups/(?P<uuid>[^/]+)/delete/$', UserGroupDelete.as_view(),
                            name='usergroup_delete'),
                        url(r'^app/(?P<username>[^/]+)/usergroups/(?P<uuid>[^/]+)/add-workspace/$',
                            WorkspacePermissionsCreate.as_view(),
                            name='asign_workspace_group'),
                        url(r'^app/(?P<username>[^/]+)/usergroups/(?P<uuid>[^/]+)/add-user/$', AddUserToGroupView.as_view(),
                            name='asign_user_group'),

                        url(r'^edit_workspace_permission$', update_workspace_permission,
                            name='edit_workspace_permission'),
                        )

urlpatterns += patterns('',
                        # goals
                        url(r'^app/(?P<username>[^/]+)/goals/$', GoalList.as_view(),
                            name='goals_list'),
                        url(r'^goals/add/$', GoalCreate.as_view(),
                            name='goals_add'),
                        url(r'^app/(?P<username>[^/]+)/goals/(?P<uuid>[^/]+)/$', GoalDetail.as_view(),
                            name='goal_detail'),
                        url(r'^app/(?P<username>[^/]+)/goals/(?P<goal_uuid>[^/]+)/snippet/(?P<uuid>[^/]+)/$',
                            SnippetDetail.as_view(),
                            name='snippet_detail'),
                        url(r'^app/(?P<username>[^/]+)/goals/(?P<uuid>[^/]+)/edit/$', GoalUpdate.as_view(),
                            name='goal_update'),
                        url(r'^app/(?P<username>[^/]+)/goals/(?P<uuid>[^/]+)/delete/$', GoalDelete.as_view(),
                            name='goal_delete'),

                        #goals search
                        #(r'^search/', include('haystack.urls')),
                        #url(r'^search-test/$', GoalSearchResults.as_view(), name='search_test'),


                        #Workspaces
                        url(r'^app/(?P<username>[^/]+)/workspaces/$', WorkspaceList.as_view(),
                            name='workspaces_list'),
                        url(r'^workspaces/add/$', WorkspaceCreate.as_view(),
                            name='workspaces_add'),
                        url(r'^app/(?P<username>[^/]+)/workspaces/(?P<uuid>[^/]+)/$', WorkspaceDetail.as_view(),
                            name='workspace_detail'),
                        url(r'^app/(?P<username>[^/]+)/workspaces/(?P<uuid>[^/]+)/edit/$', WorkspaceUpdate.as_view(),
                            name='workspace_update'),
                        url(r'^app/(?P<username>[^/]+)/workspaces/(?P<uuid>[^/]+)/delete/$', WorkspaceDelete.as_view(),
                            name='workspace_delete'),
                        url(r'^add-workspace$', add_workspace_ajax,
                            name='workspace_add_ajax'),

                        #Tags
                        url(r'^app/(?P<username>[^/]+)/tags/$', TagList.as_view(),
                            name='tags_list'),
                        url(r'^tags/add/$', TagCreate.as_view(),
                            name='tags_add'),
                        url(r'^app/(?P<username>[^/]+)/tags/(?P<uuid>[^/]+)/$', TagDetail.as_view(),
                            name='tag_detail'),
                        url(r'^app/(?P<username>[^/]+)/tags/(?P<uuid>[^/]+)/edit/$', TagUpdate.as_view(),
                            name='tag_update'),

codesnug_project/codesnug/goals/models.py
# -*- coding: utf-8 -*-
from django.db import models
from codesnug.users.models import MyUser
from codesnug.users.models import UserGroup
from codesnug.settings import WORKSPACE_PERMISSIONS, LANGUAGE_CHOICES

from uuidfield import UUIDField


class Tag(models.Model):
    title = models.CharField(max_length=50, blank=False)
    owner = models.ForeignKey(MyUser, related_name='owned_tags')
    uuid = UUIDField(auto=True)

    def __unicode__(self):
        return self.title

    class Meta:
        unique_together = (("title", "owner"),)
        ordering = ('title', )


class Workspace(models.Model):
    owner = models.ForeignKey(MyUser, related_name='owned_workspaces')
    title = models.CharField(max_length=200, blank=False)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    uuid = UUIDField(auto=True)

    def __unicode__(self):
        return self.title

    class Meta:
        unique_together = (("title", "owner"),)
        ordering = ('title', )


class WorkspacePermissions(models.Model):

    group = models.ForeignKey(UserGroup, related_name='usergroups_permissions')
    workspace = models.ForeignKey(Workspace, related_name='usergroups_permissions')
    permission = models.IntegerField(max_length=3, choices=WORKSPACE_PERMISSIONS)
    uuid = UUIDField(auto=True)

    class Meta:
        unique_together = (("group", "workspace"),)


class Goal(models.Model):
    owner = models.ForeignKey(MyUser, related_name='owned_goals')
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(Tag, blank=True, related_name='goals')
    workspaces = models.ManyToManyField(Workspace, blank=True, related_name='goals')
    is_private = models.BooleanField(default=True)
    uuid = UUIDField(auto=True)

    class Meta:
        unique_together = (("title", "owner"),)
        ordering = ('created_at', )

    def __unicode__(self):
        return self.uuid.__unicode__()

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        url = reverse("goal_detail", args=[str(self.uuid), str(self.owner.username)])
        print url
        return url


class BaseSnippet(models.Model):
    language = models.CharField(max_length=100, choices=LANGUAGE_CHOICES)
    version_number = models.IntegerField(default=1)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    uuid = UUIDField(auto=True)

    def __unicode__(self):
        return self.uuid.__unicode__()

    class Meta:
        abstract = True
        ordering = ('created_at', )


class Snippet(BaseSnippet):
    author = models.ForeignKey(MyUser, related_name='owned_snippets')
    goal = models.ForeignKey(Goal, related_name='snippets')
    title = models.CharField(max_length=200)


class Version(BaseSnippet):
    author = models.ForeignKey(MyUser, related_name='owned_versions')
    snippet = models.ForeignKey(Snippet, related_name='versions')

    class Meta:
        unique_together = (("snippet", "version_number"),)

codesnug_project/codesnug/forms.py
__author__ = 'rene'

from django import forms
from captcha.fields import ReCaptchaField


class ContactForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)
    captcha = ReCaptchaField(attrs={'theme' : 'clean'})

codesnug_project/codesnug/users/forms.py
# -*- coding: utf-8 -*-

__author__ = 'rene'

from registration.forms import RegistrationFormUniqueEmail
from django import forms
from codesnug import settings
from django.utils.translation import ugettext_lazy as _
#from django.contrib.auth.models import User
from codesnug.users.models import MyUser
from codesnug.users.lookups import MyUserLookup
from selectable.forms import AutoCompleteWidget
from awesome_avatar import forms as avatar_forms


class UserRegistrationForm(RegistrationFormUniqueEmail):
    #user
    first_name = forms.CharField(required=False, max_length=30)
    last_name = forms.CharField(required=False, max_length=100)
    email = forms.EmailField(required=True, label='Your e-mail address')
    avatar = avatar_forms.AvatarField(required=False, disable_preview=True, width=200, height=200)

    #profile
    date_of_birth = forms.DateField(required=True, input_formats=settings.DATE_INPUT_FORMATS)

    #form
    tos = forms.BooleanField(widget=forms.CheckboxInput,
                             label=_(u'I have read and agree to the Terms of Service'),
                             error_messages={'required': _("You must agree to the terms to register")})

    verify = forms.CharField(required=True, max_length=100)

    def clean_verify(self):
        if self.cleaned_data['verify'] != 'GRACIASPORLAINVITACION':
            raise forms.ValidationError(_("Currently we are in beta phase and you must have an invitation to join."))
        return self.cleaned_data['verify']


class AddUserToGroupForm(forms.Form):
    user = forms.CharField(
        label='Type the name of a user (AutoCompleteWidget)',
        widget=AutoCompleteWidget(MyUserLookup),
        required=True,
        )
    usergroup = forms.CharField(widget=forms.HiddenInput())

    def __init__(self, user, *args, **kwargs):
        super(AddUserToGroupForm, self).__init__(*args, **kwargs)
        self.fields['user'].queryset = MyUser.objects.all().exclude(pk=user.pk)


class AvatarChangeForm(forms.ModelForm):

    class Meta:
        model = MyUser
        fields = ['avatar']

codesnug_project/codesnug/api/views.py
from rest_framework.response import Response

__author__ = 'rene'
from codesnug.goals.models import Goal, Snippet, Workspace, Tag
from rest_framework import viewsets
from codesnug.api.serializers import GoalSerializer, SnippetSerializer, WorkspaceSerializer, TagSerializer

from codesnug.users.models import MyUser
from codesnug.api.serializers import MyUserSerializer


class WorkspaceViewSet(viewsets.ModelViewSet):
    serializer_class = WorkspaceSerializer
    lookup_field = 'uuid'

    def get_queryset(self):
        return Workspace.objects.filter(owner=self.request.user)

    def retrieve(self, request, *args, **kwargs):
        print "Retrieve workspace"
        self.object = self.get_object()
        serializer = self.get_serializer(self.object)
        return Response(serializer.data)


class TagViewSet(viewsets.ModelViewSet):
    serializer_class = TagSerializer
    lookup_field = 'uuid'

    def get_queryset(self):
        return Tag.objects.filter(owner=self.request.user)

    def retrieve(self, request, *args, **kwargs):
        print "Retrieve tag"
        self.object = self.get_object()
        serializer = self.get_serializer(self.object)
        return Response(serializer.data)


class GoalViewSet(viewsets.ModelViewSet):
    serializer_class = GoalSerializer
    lookup_field = 'uuid'

    def get_queryset(self):
        return Goal.objects.filter(owner=self.request.user)

    def retrieve(self, request, *args, **kwargs):
        print "Retrieve goal"
        self.object = self.get_object()
        serializer = self.get_serializer(self.object)
        return Response(serializer.data)


class SnippetViewSet(viewsets.ModelViewSet):
    serializer_class = SnippetSerializer
    lookup_field = 'uuid'

    def get_queryset(self):
        return Snippet.objects.filter(goal__owner=self.request.user)

    def retrieve(self, request, *args, **kwargs):
        print "Retrieve snippet"
        self.object = self.get_object()
        serializer = self.get_serializer(self.object)
        return Response(serializer.data)


class MyUserViewSet(viewsets.ModelViewSet):

    serializer_class = MyUserSerializer
    lookup_field = 'username'

    def get_queryset(self):
        return MyUser.objects.all()

codesnug_project/codesnug/templates/users/add_user_to_group_form.html
{% extends "users/usergroup_details.html" %}
{% load i18n %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}
{% load custom_filters %}
{% load widget_tweaks %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb_for asign_workspace_group %}
        <i class="glyphicon glyphicon-plus"></i> {% trans "Add User" %}
    {% endbreadcrumb_for %}
{% endblock %}
{% block header %}
    {% load selectable_tags %}
    {% include_jquery_libs %}
    {{ form.media }}
{% endblock %}

{% block title %}Codesnug | {% trans 'Add user to group' %}{% endblock %}

{% block content %}
<div class="container">
<div class="row" id="main-content">
    {% include 'left_sidebar.html' %}

    <div id="main-column" class="col-md-9">

        <div class="page-header">
            <h2>{% trans 'Add User to User Group' %}</h2>
        </div>
        {% render_breadcrumbs "breadcrumbs.html" %}

        {% include "messages.html" %}

        <form action="" method="post">{% csrf_token %}
            <div class="form-group {% if form.user.errors %} has-error {% endif %}">
                <label for="id_user" class="control-label">{% trans "User Name" %}</label>
                {{ form.user|addcss:'form-control' }}
                {% if form.user.errors %}
                    <ul class="help-block">
                        {% for error in form.user.errors %}
                            <li>{{ error|escape }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
            {{ form.usergroup }}
            <div class="form-group">
                <button type="submit" class="btn btn-primary">{% trans 'Add User to Group' %}</button>
            </div>
        </form>

    </div>
    </div>
    </div>
{% endblock %}

{% block footer %}
    <script src="{% static 'bootflat/js/icheck.min.js' %}"></script>
    <script type="text/javascript">
        $(function() {
            $('.checkbox input').iCheck({
                checkboxClass: 'icheckbox_flat',
                increaseArea: '20%'
            });
        });

        $(document).ready(function() {
            function formatLabel(label, item) {
                var data = label.split(',');
                return '<img src="'+data[0]+'" alt="User Avatar" class="img-rounded" width="25" height="25"/> '+data[1];
            }
            $('#id_user').djselectable('option', 'formatLabel', formatLabel);
        });
    </script>
{% endblock %}

codesnug_project/codesnug/templates/users/add_workspace_to_group_form.html
{% extends "users/usergroup_details.html" %}
{% load i18n %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}
{% load custom_filters %}
{% load widget_tweaks %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb_for asign_workspace_group %}
        <i class="glyphicon glyphicon-plus"></i> {% trans "Asign Workspace" %}
    {% endbreadcrumb_for %}
{% endblock %}

{% block title %}Codesnug | {%  trans 'Asign workspace to group' %}{% endblock %}

{% block content %}
<div class="container">
<div class="row" id="main-content">
    {% include 'left_sidebar.html' %}

    <div id="main-column" class="col-md-9">

        <div class="page-header">
            <h2>{%  trans 'Asign Workspace to User Group' %}</h2>
        </div>
        {% render_breadcrumbs "breadcrumbs.html" %}

        {% include "messages.html" %}

        <form action="" method="post">{% csrf_token %}
            <div class="form-group {% if form.workspace.errors %} has-error {% endif %}">
                <label for="id_workspace" class="control-label">{% trans "Workspace:" %}</label>
                {{ form.workspace|addcss:'form-control' }}
                {% if form.workspace.errors %}
                <ul class="help-block">
                    {% for error in form.user.errors %}
                        <li>{{ error|escape }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
            <div class="form-group {% if form.permission.errors %} has-error {% endif %}">
                <label for="id_permission" class="control-label">{% trans "Permission:" %}</label>
                {{ form.permission|addcss:'form-control' }}
                {% if form.permission.errors %}
                    <ul class="help-block">
                        {% for error in form.permission.errors %}
                            <li>{{ error|escape }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
            {{ form.usergroup }}
            <div class="form-group">
                <button type="submit" class="btn btn-primary">{% trans 'Asign Workspace to group' %}</button>
            </div>
        </form>

    </div>
    </div>
    </div>
{% endblock %}

{% block footer %}
    <script src="{% static 'bootflat/js/icheck.min.js' %}"></script>
    <script type="text/javascript">
        $(function() {
            $('.checkbox input').iCheck({
                checkboxClass: 'icheckbox_flat',
                increaseArea: '20%'
            });
        });
    </script>
{% endblock %}

codesnug_project/codesnug/templates/users/usergroup_form.html
{% extends "users/usergroup_list.html" %}
{% load i18n %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}
{% load custom_filters %}
{% load widget_tweaks %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb_for usergroup_add %}
        <i class="glyphicon glyphicon-plus"></i> {% trans "Add New" %}
    {% endbreadcrumb_for %}
{% endblock %}

{% block title %}Codesnug | {% trans 'Add new user group' %}{% endblock %}

{% block content %}
<div class="container">
<div class="row" id="main-content">
    {% include 'left_sidebar.html' %}

    <div id="main-column" class="col-md-9">

        <div class="page-header">
            <h2>{% trans 'Add User Group' %}</h2>
        </div>
        {% render_breadcrumbs "breadcrumbs.html" %}

        {% include "messages.html" %}

        <form action="" method="post">{% csrf_token %}
            <div class="form-group {% if form.title.errors %} has-error {% endif %}">
                <label for="id_title" class="control-label">{% trans "User Group Title" %}</label>
                {{ form.title|addcss:'form-control' }}
                {% if form.title.errors %}
                    <ul class="help-block">
                        {% for error in form.title.errors %}
                            <li>{{ error|escape }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
            <div class="form-group {% if form.description.errors %} has-error {% endif %}" id="description-group">
                <label for="id_description" class="control-label">{% trans "Description" %}</label>
                {{ form.description|attr:"rows:3"|addcss:'form-control' }}
                {% if form.description.errors %}
                    <ul class="help-block">
                        {% for error in form.description.errors %}
                            <li>{{ error|escape }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">{% trans 'Create User Group'%}</button>
            </div>
        </form>

    </div>
    </div>
    </div>
{% endblock %}

{% block footer %}
    <script src="{% static 'bootflat/js/icheck.min.js' %}"></script>
    <script type="text/javascript">
        $(function() {
            $('.checkbox input').iCheck({
                checkboxClass: 'icheckbox_flat',
                increaseArea: '20%'
            });
        });
    </script>
{% endblock %}

codesnug_project/codesnug/templates/users/usergroup_update_form.html
{% extends "users/usergroup_details.html" %}
{% load i18n %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}
{% load custom_filters %}
{% load widget_tweaks %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb_for 'usergroup_update' object.owner.username object.uuid %}
        <i class="glyphicon glyphicon-edit"></i> {% trans "Edit" %}
    {% endbreadcrumb_for %}
{% endblock %}

{% block title %}CodeSnug | {% trans 'Edit User Group' %}{% endblock %}

{% block content %}
<div class="container">
<div class="row" id="main-content">
    {% include 'left_sidebar.html' %}

    <div id="main-column" class="col-md-9">

        <div class="page-header">
            <h2>{% trans 'Edit User Group' %}</h2>
        </div>
        {% render_breadcrumbs "breadcrumbs.html" %}

        {% include "messages.html" %}

        <form action="" method="post">{% csrf_token %}
            <div class="form-group {% if form.title.errors %} has-error {% endif %}">
                <label for="id_title" class="control-label">{% trans "User Group Title" %}</label>
                {{ form.title|addcss:'form-control' }}
                {% if form.username.errors %}
                    <ul class="help-block">
                        {% for error in form.title.errors %}
                            <li>{{ error|escape }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
            <div class="form-group {% if form.description.errors %} has-error {% endif %}" id="description-group">
                <label for="id_description" class="control-label">{% trans "Description" %}</label>
                {{ form.description|attr:"rows:3"|addcss:'form-control' }}
                {% if form.description.errors %}
                    <ul class="help-block">
                        {% for error in form.description.errors %}
                            <li>{{ error|escape }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Update User Group</button>
            </div>
        </form>

    </div>
    </div>
{% endblock %}

{% block footer %}
    <script src="{% static 'bootflat/js/icheck.min.js' %}"></script>
    <script type="text/javascript">
        $(function() {
            $('.checkbox input').iCheck({
                checkboxClass: 'icheckbox_flat',
                increaseArea: '20%'
            });
        });
    </script>
{% endblock %}